spring:
  application:
    name: PaymentGateway

  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      timeout: 2000ms

  h2:
    console:
      enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

payment:
  gateways:
    default-gateway: ONEKHUSA

logging:
  level:
    com.paymentgateway: INFO
    org.springframework.web: INFO
